/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biblioteca.vistas;

import com.mycompany.biblioteca.controladores.ControladorLibros;
import com.mycompany.biblioteca.controladores.ControladorRegistros;
import javax.swing.JTextField;

/**
 *
 * @author tribe
 */
public class VistaRegistro extends javax.swing.JFrame {

    private ControladorRegistros controladorRegistro;

    public VistaRegistro() {
        initComponents();
        controladorRegistro = new ControladorRegistros(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCedula = new javax.swing.JLabel();
        lblBarrio = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblHoraLLegada = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtBarrio = new javax.swing.JTextField();
        txtHoraLlegada = new javax.swing.JTextField();
        btmRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTipoTarjeta = new javax.swing.JLabel();
        txtTipoTarjeta = new javax.swing.JTextField();
        btmBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btmDepurar = new javax.swing.JButton();
        btmContar = new javax.swing.JButton();
        btmListar = new javax.swing.JButton();
        btmLibros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCedula.setText("Cedula");

        lblBarrio.setText("Barrio");

        lblNombre.setText("Nombre y Apellido");

        lblHoraLLegada.setText("Hora de llegada");

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        txtHoraLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraLlegadaActionPerformed(evt);
            }
        });

        btmRegistro.setText("Registrar");
        btmRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRegistroActionPerformed(evt);
            }
        });

        jLabel1.setText("Controlador de lectores");

        lblTipoTarjeta.setText("Tipo de su tarjeta");

        btmBuscar.setText("Buscar");
        btmBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBuscarActionPerformed(evt);
            }
        });

        btmDepurar.setText("Depurar");
        btmDepurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmDepurarActionPerformed(evt);
            }
        });

        btmContar.setText("Contar");
        btmContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmContarActionPerformed(evt);
            }
        });

        btmListar.setText("Listar");
        btmListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmListarActionPerformed(evt);
            }
        });

        btmLibros.setText("Libros");
        btmLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre)
                    .addComponent(lblBarrio)
                    .addComponent(lblCedula)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTipoTarjeta)
                        .addComponent(lblHoraLLegada)
                        .addComponent(btmRegistro))
                    .addComponent(btmBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmDepurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmContar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmListar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBuscar)
                                    .addComponent(txtNombres)
                                    .addComponent(txtCedula)
                                    .addComponent(txtBarrio)
                                    .addComponent(txtHoraLlegada)
                                    .addComponent(txtTipoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btmLibros)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBarrio)
                            .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btmLibros)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoraLLegada)
                    .addComponent(txtHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoTarjeta)
                    .addComponent(txtTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmRegistro)
                    .addComponent(btmDepurar)
                    .addComponent(btmContar)
                    .addComponent(btmListar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtHoraLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraLlegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraLlegadaActionPerformed

    private void btmRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRegistroActionPerformed
        controladorRegistro.controladorRegistar();
    }//GEN-LAST:event_btmRegistroActionPerformed

    private void btmBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBuscarActionPerformed
        controladorRegistro.buscarLector();
    }//GEN-LAST:event_btmBuscarActionPerformed

    private void btmDepurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmDepurarActionPerformed
        controladorRegistro.depurarLector();
    }//GEN-LAST:event_btmDepurarActionPerformed

    private void btmContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmContarActionPerformed
        controladorRegistro.contarRegistro();
    }//GEN-LAST:event_btmContarActionPerformed

    private void btmListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmListarActionPerformed
        controladorRegistro.listarRegistro();
    }//GEN-LAST:event_btmListarActionPerformed

    private void btmLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLibrosActionPerformed
        ControladorLibros controladorLibros = new ControladorLibros(
                new VistaLibros() // Tamaño de la estantería (por ejemplo)
        );

        controladorLibros.mostrarVista(); // Muestras la nueva ventana
        this.dispose();
    }//GEN-LAST:event_btmLibrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public String getBarrio() {
        return txtBarrio.getText();
    }

    public String getCedula() {
        return txtCedula.getText();
    }

    public String getHoraLlegada() {
        return txtHoraLlegada.getText();
    }

    public String getNombres() {
        return txtNombres.getText();
    }

    public String getTxtTipoTarjeta() {
        return txtTipoTarjeta.getText();
    }

    /**
     * @param args the command line arguments
     */
    public void setTxtNombres(JTextField txtNombres) {
        this.txtNombres = txtNombres;
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmBuscar;
    private javax.swing.JButton btmContar;
    private javax.swing.JButton btmDepurar;
    private javax.swing.JButton btmLibros;
    private javax.swing.JButton btmListar;
    private javax.swing.JButton btmRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBarrio;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblHoraLLegada;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipoTarjeta;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtHoraLlegada;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTipoTarjeta;
    // End of variables declaration//GEN-END:variables
}
